insert into usr (first_name, middle_name, last_name, email) values
('Иван', 'Иванович', 'Иванов', 'ivanov@my.example.com'),
('Петр', 'Петрович', 'Петров', 'petrov@my.example.com'),
('Иван', 'Петрович', 'Сидоров', 'sidorov@my.example.com'),
('Семен', 'Семенович', 'Алексеев', 'alekseev@my.example.com'),
('Александр', 'Вячеславович', 'Савинцев', 'savintsev@my.example.com'),
('Вячеслав', 'Олегович', 'Лев', 'lev@my.example.com'),
('Денис', 'Константинович', 'Кузнецов', 'kuznrtsov@my.example.com'),
('Давид', 'Иванович', 'Горбатенков', 'gorbanenkov@my.example.com'),
('Максим', 'Артемьевич', 'Богач', 'bogash1@my.example.com'),
('Илья', 'Петрович', 'Троекуров', 'troekurov555v@my.example.com');